openapi: 3.0.0
info:
  description: API para el backend del marketplace Harbest con MongoDB
  title: API para Harbest
  version: 1.0.0
servers:
- description: Backend local
  url: http://localhost:3000
paths:
  /user:
    post:
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          description: Usuario creado exitosamente
      summary: Registrar un nuevo usuario
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
  /user/{id}:
    delete:
      operationId: deleteUser
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Usuario eliminado
      summary: Eliminar un usuario
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
    put:
      operationId: updateUser
      parameters:
      - description: ID del usuario (ObjectId)
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Usuario modificado
      summary: Modificar un usuario
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
  /farmer:
    post:
      operationId: createFarmer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Farmer"
      responses:
        "201":
          description: Agricultor creado
      summary: Registrar un nuevo agricultor
      tags:
      - Farmer
      x-eov-operation-handler: controllers/FarmerController
  /farmer/{id}:
    delete:
      operationId: farmerIdDELETE
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Eliminado
      summary: Eliminar agricultor
      tags:
      - Farmer
      x-eov-operation-handler: controllers/FarmerController
    put:
      operationId: farmerIdPUT
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Farmer"
      responses:
        "200":
          description: Agricultor modificado
      summary: Modificar un agricultor
      tags:
      - Farmer
      x-eov-operation-handler: controllers/FarmerController
  /product:
    post:
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
          description: Producto creado
      summary: Registrar un nuevo producto
      tags:
      - Product
      x-eov-operation-handler: controllers/ProductController
  /products:
    get:
      operationId: getProducts
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Product"
                type: array
          description: Lista de productos
      summary: Obtener todos los productos
      tags:
      - Product
      x-eov-operation-handler: controllers/ProductController
  /products/farmer/{id_agricultor}:
    get:
      operationId: productsFarmerIdAgricultorGET
      parameters:
      - explode: false
        in: path
        name: id_agricultor
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Product"
                type: array
          description: Lista de productos del agricultor
      summary: Obtener productos por ID de agricultor
      tags:
      - Product
      x-eov-operation-handler: controllers/ProductController
  /product/{id}:
    delete:
      operationId: productIdDELETE
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Producto eliminado
      summary: Eliminar producto
      tags:
      - Product
      x-eov-operation-handler: controllers/ProductController
    get:
      operationId: productIdGET
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
          description: Detalle del producto
      summary: Obtener un producto por ID
      tags:
      - Product
      x-eov-operation-handler: controllers/ProductController
    put:
      operationId: productIdPUT
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Producto actualizado
      summary: Modificar producto
      tags:
      - Product
      x-eov-operation-handler: controllers/ProductController
components:
  schemas:
    User:
      example:
        password: password
        id: id
        nombre: nombre
        email: email
      properties:
        id:
          readOnly: true
          type: string
        nombre:
          type: string
        email:
          format: email
          type: string
        password:
          format: password
          type: string
      type: object
    Farmer:
      example:
        password: password
        direccion: direccion
        id: id
        nombre: nombre
        email: email
      properties:
        id:
          readOnly: true
          type: string
        nombre:
          type: string
        email:
          type: string
        direccion:
          type: string
        password:
          format: password
          type: string
      type: object
    Product:
      example:
        descripcion: descripcion
        precio: 0.8008281904610115
        foto: foto
        id_agricultor: id_agricultor
        id: id
        cantidad: 6
        nombre: nombre
      properties:
        id:
          readOnly: true
          type: string
        nombre:
          type: string
        precio:
          type: number
        cantidad:
          type: integer
        descripcion:
          type: string
        id_agricultor:
          type: string
        foto:
          type: string
      type: object
